name: pokedex
description: "A new Pokédex project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.8.0

# pub.dev packages
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # http
  dio: ^5.8.0+1

  # cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # state management
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  # routes
  go_router: ^16.0.0
  flutter_web_plugins:
    sdk: flutter
  
  # dependency injection
  injectable: ^2.5.0
  get_it: ^8.0.3

  #UI
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1

  # util
  collection: ^1.19.1

# dev packages
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.5.4
  injectable_generator: ^2.1.4
  mobx_codegen: ^2.3.0
  hive_generator: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/general_icons/
    - assets/icons/nav_icons/
    - assets/icons/pokemon_types/
    - assets/images/authentication_images/
    - assets/images/general_images/
    - assets/images/onboarding_images/
    - assets/splash/
    - assets/app_prints/
