name: pokedex
description: "A new Pokédex project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.8.0

# pub.dev packages
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # state management
  flutter_mobx: ^2.3.0

  # routes
  go_router: ^16.0.0
  flutter_web_plugins:
    sdk: flutter
  
  # dependency injection
  injectable: ^2.5.0
  get_it: ^8.0.3

# dev packages
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.5.4
  injectable_generator: ^2.1.4
  mobx_codegen: ^2.3.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/authentication_images/
    - assets/general_icons/
    - assets/nav_icons/
    - assets/welcome_images/    
